# Generated by Django 4.2.24 on 2025-09-11 19:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='TipoArbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('palto', 'Palto'), ('naranjo', 'Naranjo'), ('limonero', 'Limonero'), ('manzano', 'Manzano'), ('cerezo', 'Cerezo'), ('nogal', 'Nogal'), ('almendro', 'Almendro'), ('olivo', 'Olivo'), ('durazno', 'Durazno'), ('peral', 'Peral')], max_length=20, unique=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=100)),
                ('rendimiento_base', models.FloatField(help_text='Toneladas por hectárea promedio')),
            ],
            options={
                'verbose_name': 'Tipo de Árbol',
                'verbose_name_plural': 'Tipos de Árboles',
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectareas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('edad_arboles', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('densidad_plantacion', models.IntegerField(help_text='Número de árboles por hectárea', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)])),
                ('tipo_riego', models.CharField(choices=[('goteo', 'Goteo'), ('aspersion', 'Aspersión'), ('gravedad', 'Gravedad'), ('micro_aspersion', 'Microaspersión')], max_length=20)),
                ('tipo_suelo', models.CharField(choices=[('arcilloso', 'Arcilloso'), ('arenoso', 'Arenoso'), ('franco', 'Franco'), ('limoso', 'Limoso')], max_length=20)),
                ('fertilizacion', models.CharField(choices=[('organica', 'Orgánica'), ('quimica', 'Química'), ('mixta', 'Mixta'), ('ninguna', 'Ninguna')], max_length=20)),
                ('produccion_total', models.FloatField(blank=True, help_text='Toneladas totales', null=True)),
                ('produccion_por_hectarea', models.FloatField(blank=True, help_text='Toneladas por hectárea', null=True)),
                ('confiabilidad', models.IntegerField(blank=True, help_text='Porcentaje de confiabilidad', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completada', 'Completada'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicciones.comuna')),
                ('tipo_arbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicciones.tipoarbol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='predicciones.region'),
        ),
    ]
