# Generated by Django 5.2.6 on 2025-09-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='consumo_agua_por_hectarea',
            field=models.FloatField(blank=True, help_text='Consumo de agua por hectárea en m³', null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='consumo_agua_total',
            field=models.FloatField(blank=True, help_text='Consumo total de agua en m³', null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='ingresos_proyectados_5anos',
            field=models.FloatField(blank=True, help_text='Ingresos proyectados a 5 años', null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='inversion_estimada',
            field=models.FloatField(blank=True, help_text='Inversión total estimada en CLP', null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='roi_proyectado',
            field=models.FloatField(blank=True, help_text='ROI proyectado a 5 años (%)', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoarbol',
            name='consumo_agua_m3_ton',
            field=models.FloatField(default=0, help_text='Metros cúbicos de agua por tonelada producida'),
        ),
        migrations.AddField(
            model_name='tipoarbol',
            name='costo_mantenimiento_anual',
            field=models.FloatField(default=0, help_text='Costo de mantenimiento anual por hectárea en CLP'),
        ),
        migrations.AddField(
            model_name='tipoarbol',
            name='costo_plantacion_hectarea',
            field=models.FloatField(default=0, help_text='Costo de plantación por hectárea en CLP'),
        ),
        migrations.AddField(
            model_name='tipoarbol',
            name='precio_promedio_ton',
            field=models.FloatField(default=0, help_text='Precio promedio por tonelada en CLP'),
        ),
        migrations.CreateModel(
            name='AnalisisPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('categoria_rentabilidad', models.CharField(max_length=20)),
                ('recomendacion', models.TextField()),
                ('mejor_alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_como_alternativa', to='predicciones.tipoarbol')),
                ('prediccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='predicciones.prediccion')),
            ],
            options={
                'verbose_name': 'Análisis de Predicción',
                'verbose_name_plural': 'Análisis de Predicciones',
            },
        ),
        migrations.CreateModel(
            name='DatoClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('temperatura_actual', models.FloatField()),
                ('humedad', models.IntegerField()),
                ('descripcion_clima', models.CharField(max_length=100)),
                ('icono_clima', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicciones.comuna')),
            ],
            options={
                'verbose_name': 'Dato Climático',
                'verbose_name_plural': 'Datos Climáticos',
                'unique_together': {('comuna', 'fecha')},
            },
        ),
    ]
